DATA:
  data_name: mnist
  data_dir: data
  workers: 2
  

LOGS:
  res_dir: results


TRAIN:
  data_aug: True
  batch_size: 128
  epochs: 100
  lr: 0.01
  weight_decay: 0
  momentum: 0.9
  log_interval: 10
  seed: 1
  debug: False
  model_dir: model_ckpt/
  pretrain: False
  aux_data_filename: None
  svhn_extra: False
  remove_pseudo_labels: False
  aux_take_amount: -1
  unsup_fraction : 0.5
  lr_schedule: 'trades_fixed'
  entropy_weight: 0
  unlabeled: False
  nesterov: False
  eval_freq: 1

TEST:
  val_batch_size: 500
  eval_pgd_steps: 40
  individual: False
  n_ex: 10000
  test_filename: 'small_cnn-100.pt'


MODEL:
  save_freq: 1
  arch: cnn

PGD:
  random_init: True
  epsilon: 0.3
  perturb_steps: 40
  step_size: 0.01
  distance: 'Linf'
  eps: 0.000001

APGD:
  n_restarts: 1
  eot_iter: 1
  rho: .75
  verbose: False
  device: 'cuda'


RAO:
  beta: 20.0

DISTRIBUTED:
  gpus: [0,1]





